config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'shares#index'
  resources :shares do
  end
  resource :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distance.rb
class Distance < ActiveHash::Base
  self.data = [
    {id: 1, name: '5km'}, {id: 2, name: '10km'}, {id: 3, name: '15km'},
    {id: 4, name: '20km'}, {id: 5, name: '25km'}, {id: 6, name: '30km'},
    {id: 7, name: '35km'}, {id: 8, name: '40km'}, {id: 9, name: '45km'},
    {id: 10, name: '50km'}, {id: 11, name: '55km'}, {id: 12, name: '60km'},
    {id: 13, name: '65km'}, {id: 14, name: '70km'}, {id: 15, name: '75km'},
    {id: 16, name: '80km'}, {id: 17, name: '90km'}, {id: 18, name: '95km'},
    {id: 19, name: '95km'}, {id: 20, name: '100km'}
    ]
end

app/models/elevation.rb
class  Elevation < ActiveHash::Base
  self.data = [
    {id: 1, name: '0m'}, {id: 2, name: '10m'}, {id: 3, name: '20m'},
    {id: 4, name: '30m'}, {id: 5, name: '40m'}, {id: 6, name: '50m'},
    {id: 7, name: '60m'}, {id: 8, name: '70m'}, {id: 9, name: '80m'},
    {id: 10, name: '90m'}, {id: 11, name: '100m'}, {id: 12, name: '110m'},
    {id: 13, name: '120m'}, {id: 14, name: '130m'}, {id: 15, name: '140m'},
    {id: 16, name: '150m'}, {id: 17, name: '160m'}, {id: 18, name: '170m'},
    {id: 19, name: '180m'}, {id: 20, name: '190m'}
    ]
end

app/models/human.rb
class Human < ActiveHash::Base
  self.data = [
    {id: 1, name: '1人'}, {id: 2, name: '2人'}, {id: 3, name: '3人'},
    {id: 4, name: '4人'}, {id: 5, name: '5人'}, {id: 6, name: '6人'},
    {id: 7, name: '7人'}, {id: 8, name: '8人'}, {id: 9, name: '9人'},
    {id: 10, name: '10人'}, {id: 11, name: '11人'}, {id: 12, name: '12人'},
    {id: 13, name: '13人'}, {id: 14, name: '14人'}, {id: 15, name: '15人'},
    {id: 16, name: '16人'}, {id: 17, name: '17人'}, {id: 18, name: '18人'},
    {id: 19, name: '19人'}, {id: 20, name: '20人'}
    ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/share.rb
class Share < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :share_images, dependent: :destroy
  accepts_nested_attributes_for :share_images

belongs_to_active_hash :prefecture
belongs_to_active_hash :human
belongs_to_active_hash :distance
belongs_to_active_hash :elevation

delegate :name, to: :prefecture
belongs_to :user
mount_uploader :image, ImageUploader

end

app/models/share_image.rb
class ShareImage < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shares
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :basic_auth, if: :production?
  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController

  before_action :move_to_index, except: :index
  before_action :set_share, only: [:show, :edit, :update]

  def index
    @shares = Share.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @share = Share.new
    @share.share_images.build
  end

  def create
    @share = Share.new(share_params)
    if @share.save && new_image_params[:images][0] != " "
      new_image_params[:images].each do |image|
        @share.share_images.create(image_url: image, share_id: @share.id)
      end
      redirect_to root_path
    else
      @share.share_images.bulid
      rendre :new
    end
  end

  def show
    @share = Share.find[params[:id]]
  end

  private
  def share_params
    params.require(:share).permit(:content, :remarks, :prefecture_id, :human_id,  :elevation_id, :distance_id).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_share
    @share = Share.find(params[:id])
  end

  def new_image_params
    params.require(:share_images).permit({images: []})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @shares = Share.where(user_id: current_user.id).page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width"}
    %title RideShare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true }}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
  %body
= yield

app/views/shared/_main-hedaer.html.haml
%h1.title
  = link_to(root_path) do
    %p RIDE SHARE
    - if user_signed_in?
      .user__signed__menu
        = link_to "logout", destroy_user_session_path, method: :delete
        %a.post{:href => "/shares/new"} new
    - else
      = link_to "login", new_user_session_path
      = link_to "sign up", new_user_registration_path

app/views/shares/_share.html.haml
= link_to share_path(share.id), class: 'share-link' do
  .share{:style => "background-image: url(#{share.image});"}
    %p.share__content
      = share.content
    .share__name
      .share__name__text
        %span 投稿者
      .share__name__text
        %span nori

app/views/shares/botan.html.haml
.dropdown.drop-hover
  %button.btn.btn-secondary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
    ドロップダウンボタン
  %ul.dropdown-menu
    %li.dropright.drop-hover
      %a.dropdown-item.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} メニュー
      %ul.dropdown-menu
        %li.dropright.drop-hover
          %a.dropdown-item.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} メニュー
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => "#"} メニュー
            %li
              %a.dropdown-item{:href => "#"} メニュー
        %li
          %a.dropdown-item{:href => "#"} メニュー
        %li
          %a.dropdown-item{:href => "#"} メニュー
    %li
      %a.dropdown-item{:href => "#"} メニュー
:css
  .drop-hover:hover > .dropdown-menu {
    display: block !important;
  }

app/views/shares/index.html.haml
.main-page
  = render "shared/main-hedaer"
  .main__contents
    - @shares.each do |share|
      = render partial: share, locals: { share: share}
    = paginate(@shares)

app/views/shares/new.html.haml
.new__shares
  %h3.new__shares__text
    らいど いきましょ
  .new-form
    .new-form__content
      = form_with model: @share do |f|
        .upload-box
          = f.fields_for :share_images, @share.share_images.first do |image|
            .upload-box__dropbox
              #preview
              .upload-box__dropbox__container
                = image.label :image, for: "upload-image" do
                  .upload-box__dropbox__container__list
                    = image.file_field :image_url,multiple: "multiple", id:"upload-image", 'data-image': 0
                  .upload-box__dropbox__container__frame
                    %p.upload-box__dropbox__container__frame__explain
                      最大3枚までアップロードできます
        = f.text_field :content, class: 'form__message', placeholder: 'らいどさき', maxlength: "20"
        -# = f.label :image, class: 'form__image' do
        -#   = fa_icon 'picture-o', class: 'icon3'
        -#   = f.file_field :image, class: 'hidden'
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name,  {prompt: "ばしょ"}, {class: 'form__select'}
        = f.collection_select :human_id, Human.all, :id, :name, {prompt: "にんずう"}, {class: "form__select"}
        = f.collection_select :distance_id, Distance.all, :id, :name, {prompt: "きょり"}, {class: "form__select"}
        = f.collection_select :elevation_id, Elevation.all, :id, :name, {prompt: "こうていさ"}, {class: "form__select"}
        = f.text_area :remarks, class:'form__remarks', placeholder: 'びこうらん'
        = f.submit 'Send', class: 'btn btn-primary btn-sm'

app/views/users/show.html.haml
.show
  %p
    = @name
    さんの投稿一覧
  - @shares.each do |share|
    .share{:style => "background-image: url(#{share.image});"}
      = simple_format(share.content)
  = paginate(@shares)